### ISSUE TITLE
add option to change toc style

### ISSUE THREAD

**Issue by vikyd** [zq99299/gitbook-plugin-anchor-navigation-ex#2]
add option to change toc style, such as:
- bigger front
- no point before

**Comment by zq99299** [comment]
I don't quite understand what your brief description is. Can you give an example

不太明白你这简短的描述是想要什么效果。能否举个例子

**Comment by zq99299** [comment]
In front of you in the TOC header dot?
- Whether display dot?


你的意思 toc 标题中前面的 小圆点？
-  是否显示小圆点？

**Comment by vikyd** [comment]
对

已通过 CSS 解决了，在`styles/website.css` 中增加下面代码就行了：
```css
#anchor-navigation-ex-navbar li {
    list-style-type: none;
}
```
